/**
 * Field Registry Data - Static field definitions for reportable entities
 *
 * Contains hardcoded field catalogs for all reportable entity types.
 * These are static fields from the Prisma schema, not dynamic custom properties.
 *
 * Extracted from ReportFieldRegistryService for maintainability.
 */

import { ReportFieldType } from "../entities/saved-report.entity";

/**
 * Internal field definition with full metadata
 */
export interface FieldDefinition {
  id: string;
  label: string;
  type: ReportFieldType;
  group: string;
  prismaField: string;
  filterable: boolean;
  sortable: boolean;
  groupable: boolean;
  aggregatable: boolean;
  enumValues?: string[];
  isComputed?: boolean;
  isCustomProperty?: boolean;
  joinPath?: string;
}

/**
 * Static field registries for each entity type
 */
export const ENTITY_FIELD_REGISTRIES: Record<string, FieldDefinition[]> = {
  // ==========================================
  // CASES - Primary compliance work container
  // ==========================================
  cases: [
    // Case Details
    {
      id: "id",
      label: "Case ID",
      type: "uuid",
      group: "Case Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "referenceNumber",
      label: "Reference Number",
      type: "string",
      group: "Case Details",
      prismaField: "referenceNumber",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Case Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["NEW", "IN_PROGRESS", "PENDING", "CLOSED", "MERGED"],
    },
    {
      id: "outcome",
      label: "Outcome",
      type: "enum",
      group: "Case Details",
      prismaField: "outcome",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "SUBSTANTIATED",
        "UNSUBSTANTIATED",
        "INCONCLUSIVE",
        "NO_ACTION_REQUIRED",
        "REFERRED",
      ],
    },
    {
      id: "pipelineStage",
      label: "Pipeline Stage",
      type: "string",
      group: "Case Details",
      prismaField: "pipelineStage",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "severity",
      label: "Severity",
      type: "enum",
      group: "Case Details",
      prismaField: "severity",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    },
    {
      id: "caseType",
      label: "Case Type",
      type: "enum",
      group: "Case Details",
      prismaField: "caseType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "REPORT",
        "REQUEST_INFO",
        "QUESTION",
        "COMPLIMENT",
        "FOLLOW_UP",
      ],
    },
    {
      id: "sourceChannel",
      label: "Source Channel",
      type: "enum",
      group: "Case Details",
      prismaField: "sourceChannel",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "PHONE",
        "WEB_FORM",
        "EMAIL",
        "CHATBOT",
        "PROXY",
        "IMPORTED",
      ],
    },
    {
      id: "tags",
      label: "Tags",
      type: "string",
      group: "Case Details",
      prismaField: "tags",
      filterable: true,
      sortable: false,
      groupable: false,
      aggregatable: false,
    },

    // Classification
    {
      id: "primaryCategoryId",
      label: "Primary Category ID",
      type: "uuid",
      group: "Classification",
      prismaField: "primaryCategoryId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "primaryCategoryName",
      label: "Primary Category",
      type: "string",
      group: "Classification",
      prismaField: "primaryCategory.name",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "primaryCategory",
    },
    {
      id: "secondaryCategoryId",
      label: "Secondary Category ID",
      type: "uuid",
      group: "Classification",
      prismaField: "secondaryCategoryId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "secondaryCategoryName",
      label: "Secondary Category",
      type: "string",
      group: "Classification",
      prismaField: "secondaryCategory.name",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "secondaryCategory",
    },

    // Assignment
    {
      id: "createdById",
      label: "Created By ID",
      type: "uuid",
      group: "Assignment",
      prismaField: "createdById",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "createdByName",
      label: "Created By",
      type: "string",
      group: "Assignment",
      prismaField: "createdBy.firstName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "createdBy",
    },
    {
      id: "intakeOperatorId",
      label: "Intake Operator ID",
      type: "uuid",
      group: "Assignment",
      prismaField: "intakeOperatorId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "intakeOperatorName",
      label: "Intake Operator",
      type: "string",
      group: "Assignment",
      prismaField: "intakeOperator.firstName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "intakeOperator",
    },

    // Reporter
    {
      id: "reporterType",
      label: "Reporter Type",
      type: "enum",
      group: "Reporter",
      prismaField: "reporterType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["ANONYMOUS", "CONFIDENTIAL", "IDENTIFIED"],
    },
    {
      id: "reporterAnonymous",
      label: "Is Anonymous",
      type: "boolean",
      group: "Reporter",
      prismaField: "reporterAnonymous",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "reporterRelationship",
      label: "Reporter Relationship",
      type: "enum",
      group: "Reporter",
      prismaField: "reporterRelationship",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "EMPLOYEE",
        "FORMER_EMPLOYEE",
        "CONTRACTOR",
        "VENDOR",
        "CUSTOMER",
        "OTHER",
      ],
    },

    // Location
    {
      id: "locationCity",
      label: "City",
      type: "string",
      group: "Location",
      prismaField: "locationCity",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationState",
      label: "State/Province",
      type: "string",
      group: "Location",
      prismaField: "locationState",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationCountry",
      label: "Country",
      type: "string",
      group: "Location",
      prismaField: "locationCountry",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },

    // Timestamps
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "intakeTimestamp",
      label: "Intake Time",
      type: "datetime",
      group: "Timestamps",
      prismaField: "intakeTimestamp",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "outcomeAt",
      label: "Outcome At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "outcomeAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "releasedAt",
      label: "Released At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "releasedAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },

    // Metrics (computed)
    {
      id: "daysOpen",
      label: "Days Open",
      type: "number",
      group: "Metrics",
      prismaField: "daysOpen",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
      isComputed: true,
    },

    // AI Fields
    {
      id: "aiSummary",
      label: "AI Summary",
      type: "string",
      group: "AI",
      prismaField: "aiSummary",
      filterable: false,
      sortable: false,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "aiConfidenceScore",
      label: "AI Confidence",
      type: "number",
      group: "AI",
      prismaField: "aiConfidenceScore",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
  ],

  // ==========================================
  // RIUS - Risk Intelligence Units (immutable inputs)
  // ==========================================
  rius: [
    {
      id: "id",
      label: "RIU ID",
      type: "uuid",
      group: "RIU Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "referenceNumber",
      label: "Reference Number",
      type: "string",
      group: "RIU Details",
      prismaField: "referenceNumber",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "type",
      label: "RIU Type",
      type: "enum",
      group: "RIU Details",
      prismaField: "type",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "HOTLINE_REPORT",
        "WEB_FORM_SUBMISSION",
        "DISCLOSURE_RESPONSE",
        "EMAIL_INTAKE",
        "CHATBOT_TRANSCRIPT",
      ],
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "RIU Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["PENDING_QA", "IN_QA", "RELEASED", "REJECTED"],
    },
    {
      id: "severity",
      label: "Severity",
      type: "enum",
      group: "RIU Details",
      prismaField: "severity",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["LOW", "MEDIUM", "HIGH", "CRITICAL"],
    },
    {
      id: "sourceChannel",
      label: "Source Channel",
      type: "enum",
      group: "Source",
      prismaField: "sourceChannel",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["PHONE", "WEB_FORM", "EMAIL", "CHATBOT", "PROXY"],
    },
    {
      id: "campaignId",
      label: "Campaign ID",
      type: "uuid",
      group: "Source",
      prismaField: "campaignId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "categoryId",
      label: "Category ID",
      type: "uuid",
      group: "Classification",
      prismaField: "categoryId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "categoryName",
      label: "Category",
      type: "string",
      group: "Classification",
      prismaField: "category.name",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "category",
    },
    {
      id: "reporterType",
      label: "Reporter Type",
      type: "enum",
      group: "Reporter",
      prismaField: "reporterType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["ANONYMOUS", "CONFIDENTIAL", "IDENTIFIED"],
    },
    {
      id: "locationCity",
      label: "City",
      type: "string",
      group: "Location",
      prismaField: "locationCity",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationState",
      label: "State/Province",
      type: "string",
      group: "Location",
      prismaField: "locationState",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationCountry",
      label: "Country",
      type: "string",
      group: "Location",
      prismaField: "locationCountry",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "aiSummary",
      label: "AI Summary",
      type: "string",
      group: "AI",
      prismaField: "aiSummary",
      filterable: false,
      sortable: false,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "aiRiskScore",
      label: "AI Risk Score",
      type: "number",
      group: "AI",
      prismaField: "aiRiskScore",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
    {
      id: "aiLanguageDetected",
      label: "Language Detected",
      type: "string",
      group: "AI",
      prismaField: "aiLanguageDetected",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
  ],

  // ==========================================
  // PERSONS - Individuals in the system
  // ==========================================
  persons: [
    {
      id: "id",
      label: "Person ID",
      type: "uuid",
      group: "Person Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "type",
      label: "Person Type",
      type: "enum",
      group: "Person Details",
      prismaField: "type",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "EMPLOYEE",
        "SUBJECT",
        "WITNESS",
        "EXTERNAL_CONTACT",
        "UNKNOWN",
      ],
    },
    {
      id: "source",
      label: "Source",
      type: "enum",
      group: "Person Details",
      prismaField: "source",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["HRIS", "MANUAL", "INTAKE", "DISCLOSURE"],
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Person Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["ACTIVE", "INACTIVE", "TERMINATED", "MERGED"],
    },
    {
      id: "employeeId",
      label: "Employee ID",
      type: "string",
      group: "Employment",
      prismaField: "employeeId",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "jobTitle",
      label: "Job Title",
      type: "string",
      group: "Employment",
      prismaField: "jobTitle",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "employmentStatus",
      label: "Employment Status",
      type: "string",
      group: "Employment",
      prismaField: "employmentStatus",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "businessUnitId",
      label: "Business Unit ID",
      type: "uuid",
      group: "Organization",
      prismaField: "businessUnitId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "businessUnitName",
      label: "Business Unit",
      type: "string",
      group: "Organization",
      prismaField: "businessUnitName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationId",
      label: "Location ID",
      type: "uuid",
      group: "Organization",
      prismaField: "locationId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "locationName",
      label: "Location",
      type: "string",
      group: "Organization",
      prismaField: "locationName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "managerId",
      label: "Manager ID",
      type: "uuid",
      group: "Organization",
      prismaField: "managerId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "managerName",
      label: "Manager",
      type: "string",
      group: "Organization",
      prismaField: "managerName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
  ],

  // ==========================================
  // CAMPAIGNS - Disclosure/attestation campaigns
  // ==========================================
  campaigns: [
    {
      id: "id",
      label: "Campaign ID",
      type: "uuid",
      group: "Campaign Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "name",
      label: "Name",
      type: "string",
      group: "Campaign Details",
      prismaField: "name",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "type",
      label: "Campaign Type",
      type: "enum",
      group: "Campaign Details",
      prismaField: "type",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["DISCLOSURE", "ATTESTATION", "SURVEY"],
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Campaign Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "DRAFT",
        "SCHEDULED",
        "ACTIVE",
        "PAUSED",
        "COMPLETED",
        "CANCELLED",
      ],
    },
    {
      id: "version",
      label: "Version",
      type: "number",
      group: "Campaign Details",
      prismaField: "version",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "launchAt",
      label: "Scheduled Launch",
      type: "datetime",
      group: "Schedule",
      prismaField: "launchAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "launchedAt",
      label: "Actual Launch",
      type: "datetime",
      group: "Schedule",
      prismaField: "launchedAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "dueDate",
      label: "Due Date",
      type: "datetime",
      group: "Schedule",
      prismaField: "dueDate",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "expiresAt",
      label: "Expiration",
      type: "datetime",
      group: "Schedule",
      prismaField: "expiresAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "audienceMode",
      label: "Audience Mode",
      type: "enum",
      group: "Audience",
      prismaField: "audienceMode",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["ALL", "SEGMENT", "MANUAL"],
    },
    {
      id: "totalAssignments",
      label: "Total Assignments",
      type: "number",
      group: "Audience",
      prismaField: "totalAssignments",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
    {
      id: "completedAssignments",
      label: "Completed",
      type: "number",
      group: "Progress",
      prismaField: "completedAssignments",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
    {
      id: "overdueAssignments",
      label: "Overdue",
      type: "number",
      group: "Progress",
      prismaField: "overdueAssignments",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
    {
      id: "completionPercentage",
      label: "Completion %",
      type: "number",
      group: "Progress",
      prismaField: "completionPercentage",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: true,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
  ],

  // ==========================================
  // POLICIES - Policy documents
  // ==========================================
  policies: [
    {
      id: "id",
      label: "Policy ID",
      type: "uuid",
      group: "Policy Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "title",
      label: "Title",
      type: "string",
      group: "Policy Details",
      prismaField: "title",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "slug",
      label: "Slug",
      type: "string",
      group: "Policy Details",
      prismaField: "slug",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "policyType",
      label: "Policy Type",
      type: "enum",
      group: "Policy Details",
      prismaField: "policyType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["POLICY", "PROCEDURE", "GUIDELINE", "STANDARD"],
    },
    {
      id: "category",
      label: "Category",
      type: "string",
      group: "Policy Details",
      prismaField: "category",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Policy Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "DRAFT",
        "PENDING_REVIEW",
        "APPROVED",
        "PUBLISHED",
        "RETIRED",
      ],
    },
    {
      id: "currentVersion",
      label: "Current Version",
      type: "number",
      group: "Version",
      prismaField: "currentVersion",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "ownerId",
      label: "Owner ID",
      type: "uuid",
      group: "Ownership",
      prismaField: "ownerId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "ownerName",
      label: "Owner",
      type: "string",
      group: "Ownership",
      prismaField: "owner.firstName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "owner",
    },
    {
      id: "effectiveDate",
      label: "Effective Date",
      type: "date",
      group: "Dates",
      prismaField: "effectiveDate",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "reviewDate",
      label: "Review Date",
      type: "date",
      group: "Dates",
      prismaField: "reviewDate",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "retiredAt",
      label: "Retired At",
      type: "datetime",
      group: "Dates",
      prismaField: "retiredAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
  ],

  // ==========================================
  // DISCLOSURES - Disclosure form submissions
  // ==========================================
  disclosures: [
    {
      id: "id",
      label: "Disclosure ID",
      type: "uuid",
      group: "Disclosure Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "disclosureType",
      label: "Disclosure Type",
      type: "enum",
      group: "Disclosure Details",
      prismaField: "disclosureType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "CONFLICT_OF_INTEREST",
        "GIFT",
        "ENTERTAINMENT",
        "OUTSIDE_ACTIVITY",
        "FINANCIAL_INTEREST",
      ],
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Disclosure Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "DRAFT",
        "SUBMITTED",
        "UNDER_REVIEW",
        "APPROVED",
        "REJECTED",
        "REQUIRES_ACTION",
      ],
    },
    {
      id: "riskLevel",
      label: "Risk Level",
      type: "enum",
      group: "Review",
      prismaField: "riskLevel",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["LOW", "MEDIUM", "HIGH"],
    },
    {
      id: "reviewedAt",
      label: "Reviewed At",
      type: "datetime",
      group: "Review",
      prismaField: "reviewedAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "submittedByEmployeeId",
      label: "Submitter Employee ID",
      type: "uuid",
      group: "Submitter",
      prismaField: "submittedByEmployeeId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "submittedAt",
      label: "Submitted At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "submittedAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
  ],

  // ==========================================
  // INVESTIGATIONS - Formal investigations
  // ==========================================
  investigations: [
    {
      id: "id",
      label: "Investigation ID",
      type: "uuid",
      group: "Investigation Details",
      prismaField: "id",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "investigationNumber",
      label: "Investigation #",
      type: "number",
      group: "Investigation Details",
      prismaField: "investigationNumber",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
    {
      id: "caseId",
      label: "Case ID",
      type: "uuid",
      group: "Investigation Details",
      prismaField: "caseId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "investigationType",
      label: "Investigation Type",
      type: "enum",
      group: "Investigation Details",
      prismaField: "investigationType",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["FULL", "PRELIMINARY", "EXPEDITED", "FOLLOW_UP"],
    },
    {
      id: "status",
      label: "Status",
      type: "enum",
      group: "Investigation Details",
      prismaField: "status",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "NEW",
        "IN_PROGRESS",
        "PENDING_REVIEW",
        "ON_HOLD",
        "COMPLETED",
        "CANCELLED",
      ],
    },
    {
      id: "outcome",
      label: "Outcome",
      type: "enum",
      group: "Investigation Details",
      prismaField: "outcome",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "SUBSTANTIATED",
        "UNSUBSTANTIATED",
        "INCONCLUSIVE",
        "PARTIALLY_SUBSTANTIATED",
        "REFERRED",
      ],
    },
    {
      id: "primaryInvestigatorId",
      label: "Primary Investigator ID",
      type: "uuid",
      group: "Assignment",
      prismaField: "primaryInvestigatorId",
      filterable: true,
      sortable: false,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "primaryInvestigatorName",
      label: "Primary Investigator",
      type: "string",
      group: "Assignment",
      prismaField: "primaryInvestigator.firstName",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      joinPath: "primaryInvestigator",
    },
    {
      id: "department",
      label: "Department",
      type: "enum",
      group: "Assignment",
      prismaField: "department",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: [
        "COMPLIANCE",
        "HR",
        "LEGAL",
        "INTERNAL_AUDIT",
        "SECURITY",
        "OTHER",
      ],
    },
    {
      id: "dueDate",
      label: "Due Date",
      type: "date",
      group: "Timeline",
      prismaField: "dueDate",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "slaStatus",
      label: "SLA Status",
      type: "enum",
      group: "Timeline",
      prismaField: "slaStatus",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
      enumValues: ["ON_TRACK", "AT_RISK", "OVERDUE"],
    },
    {
      id: "closedAt",
      label: "Closed At",
      type: "datetime",
      group: "Timeline",
      prismaField: "closedAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "createdAt",
      label: "Created At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "createdAt",
      filterable: true,
      sortable: true,
      groupable: true,
      aggregatable: false,
    },
    {
      id: "updatedAt",
      label: "Updated At",
      type: "datetime",
      group: "Timestamps",
      prismaField: "updatedAt",
      filterable: true,
      sortable: true,
      groupable: false,
      aggregatable: false,
    },
  ],
};

/**
 * Map CustomPropertyDefinition entityType to report entity type
 */
export const CUSTOM_PROPERTY_ENTITY_MAP: Record<string, string> = {
  CASE: "cases",
  INVESTIGATION: "investigations",
  PERSON: "persons",
  RIU: "rius",
};

/**
 * Map PropertyDataType to ReportFieldType
 */
export const PROPERTY_TYPE_MAP: Record<string, ReportFieldType> = {
  TEXT: "string",
  NUMBER: "number",
  DATE: "date",
  DATETIME: "datetime",
  SELECT: "enum",
  MULTI_SELECT: "enum",
  BOOLEAN: "boolean",
  URL: "string",
  EMAIL: "string",
  PHONE: "string",
};

/**
 * Group order for consistent UI display
 */
export const FIELD_GROUP_ORDER = [
  "Case Details",
  "RIU Details",
  "Person Details",
  "Campaign Details",
  "Policy Details",
  "Disclosure Details",
  "Investigation Details",
  "Classification",
  "Source",
  "Assignment",
  "Reporter",
  "Employment",
  "Organization",
  "Location",
  "Ownership",
  "Schedule",
  "Audience",
  "Progress",
  "Review",
  "Submitter",
  "Version",
  "Timeline",
  "Dates",
  "Timestamps",
  "Metrics",
  "AI",
  "Custom Properties",
];
