/**
 * Type definitions for user-created tables (RS.48)
 */

// Re-export enums that will be generated by Prisma
// These are duplicated here for TypeScript reference before Prisma generate
export type TableCreationMethodType = "BUILDER" | "AI_GENERATED" | "IMPORT";
export type TableVisibilityType = "PRIVATE" | "TEAM" | "ORG";

/**
 * Column definition for user data tables.
 * Extends the report column pattern with additional display options.
 */
export interface TableColumn {
  /** Field name in the data source (e.g., 'status', 'createdAt') */
  field: string;

  /** Human-readable label for display */
  label: string;

  /** Data type for formatting */
  type: "string" | "number" | "date" | "boolean" | "currency";

  /** Format string (date format, number decimals, etc.) */
  format?: string;

  /** Column width in characters */
  width?: number;
}

/**
 * Filter criteria for table queries.
 */
export interface TableFilterCriteria {
  /** Field name to filter on */
  field: string;

  /** Comparison operator */
  operator:
    | "eq"
    | "neq"
    | "gt"
    | "gte"
    | "lt"
    | "lte"
    | "in"
    | "contains"
    | "between"
    | "isNull"
    | "isNotNull";

  /** Value to compare against */
  value: unknown;
}

/**
 * Aggregate definition for grouped table results.
 */
export interface TableAggregateDefinition {
  /** Field to aggregate */
  field: string;

  /** Aggregation function */
  function: "count" | "sum" | "avg" | "min" | "max";

  /** Optional alias for the result column */
  alias?: string;
}

/**
 * Sort definition for table results.
 */
export interface TableSortDefinition {
  /** Field to sort by */
  field: string;

  /** Sort direction */
  direction: "asc" | "desc";
}

/**
 * Destination where a table is pinned.
 */
export interface TableDestination {
  /** Type of destination */
  type: "dashboard" | "view" | "report";

  /** ID of the destination (dashboard ID, view ID, etc.) */
  id?: string;

  /** Display name for the pinned location */
  name?: string;
}

/**
 * Schedule configuration for automated table delivery.
 */
export interface TableScheduleConfig {
  /** Delivery frequency */
  frequency: "daily" | "weekly" | "monthly";

  /** Email recipients (user IDs or email addresses) */
  recipients: string[];

  /** Export format */
  format: "csv" | "excel" | "pdf";

  /** Day of week for weekly schedules (0 = Sunday, 6 = Saturday) */
  dayOfWeek?: number;

  /** Day of month for monthly schedules (1-28) */
  dayOfMonth?: number;

  /** Time of day to send (HH:mm format, 24-hour) */
  time?: string;

  /** Timezone for scheduling */
  timezone?: string;
}

/**
 * Result from executing a table query.
 */
export interface TableQueryResult {
  /** Data rows */
  data: Record<string, unknown>[];

  /** Total count of matching records (before pagination) */
  total: number;

  /** Column metadata */
  columns: TableColumn[];

  /** Aggregation results (if groupBy was used) */
  aggregations?: Record<string, unknown>[];
}

/**
 * Parameters for sharing a table.
 */
export interface TableShareParams {
  /** Visibility level */
  visibility: TableVisibilityType;

  /** Team IDs to share with (when visibility = TEAM) */
  teamIds?: string[];

  /** User IDs to share with (when visibility = TEAM or for additional access) */
  userIds?: string[];
}

/**
 * Query parameters for listing tables.
 */
export interface TableListQuery {
  /** Filter by visibility */
  visibility?: TableVisibilityType;

  /** Filter by creation method */
  createdVia?: TableCreationMethodType;

  /** Search by name */
  search?: string;

  /** Include only tables pinned to a specific destination */
  pinnedTo?: {
    type: "dashboard" | "view" | "report";
    id?: string;
  };

  /** Pagination */
  limit?: number;
  offset?: number;
}

/**
 * Supported data sources for tables (maps to Prisma models).
 */
export type TableDataSource =
  | "cases"
  | "investigations"
  | "rius"
  | "campaigns"
  | "campaign_assignments"
  | "disclosures"
  | "employees"
  | "persons"
  | "users"
  | "audit_logs";

/**
 * Export parameters for table data.
 */
export interface TableExportParams {
  /** Export format */
  format: "csv" | "excel" | "pdf";

  /** Optional filename (without extension) */
  filename?: string;

  /** Include table metadata in export */
  includeMetadata?: boolean;
}
