import { Module } from "@nestjs/common";
import { JwtModule } from "@nestjs/jwt";
import { PassportModule } from "@nestjs/passport";
import { ConfigModule, ConfigService } from "@nestjs/config";
import { AuthService } from "./auth.service";
import { AuthController } from "./auth.controller";
import {
  JwtStrategy,
  AzureAdStrategy,
  GoogleStrategy,
  SamlStrategy,
} from "./strategies";
import { DomainModule } from "./domain";
import { SsoModule } from "./sso";
import { MfaModule } from "./mfa";
import { JwtKeyService } from "./services";

@Module({
  imports: [
    PassportModule.register({ defaultStrategy: "jwt" }),
    JwtModule.registerAsync({
      imports: [ConfigModule],
      inject: [ConfigService],
      useFactory: (configService: ConfigService) => {
        // Determine algorithm based on RS256 key availability
        const privateKey = configService.get<string>("jwt.rs256.privateKey");
        const publicKey = configService.get<string>("jwt.rs256.publicKey");
        const nodeEnv = configService.get<string>("nodeEnv");

        // RS256 if keys configured OR in development (auto-generated keys)
        const useRs256 = (privateKey && publicKey) || nodeEnv !== "production";

        if (useRs256 && privateKey && publicKey) {
          // Production RS256 with configured keys
          return {
            privateKey: normalizeKey(privateKey),
            publicKey: normalizeKey(publicKey),
            signOptions: {
              algorithm: "RS256" as const,
              expiresIn: configService.get<string>(
                "jwt.accessTokenExpiry",
                "15m",
              ),
            },
            verifyOptions: {
              algorithms: ["RS256", "HS256"] as const, // Accept both during migration
            },
          };
        }

        // Development (keys auto-generated by JwtKeyService) or HS256 fallback
        // JwtKeyService provides signing key dynamically
        return {
          secret: configService.get<string>("jwt.secret"),
          signOptions: {
            expiresIn: configService.get<string>(
              "jwt.accessTokenExpiry",
              "15m",
            ),
          },
        };
      },
    }),
    DomainModule,
    SsoModule,
    MfaModule,
  ],
  controllers: [AuthController],
  providers: [
    AuthService,
    JwtKeyService,
    JwtStrategy,
    AzureAdStrategy,
    GoogleStrategy,
    SamlStrategy,
  ],
  exports: [
    AuthService,
    JwtModule,
    JwtKeyService,
    DomainModule,
    SsoModule,
    MfaModule,
  ],
})
export class AuthModule {}

/**
 * Normalizes PEM key format (handles base64-encoded or escaped newlines).
 */
function normalizeKey(key: string): string {
  // If key is base64-encoded (no PEM headers), decode it
  if (!key.includes("-----BEGIN")) {
    try {
      const decoded = Buffer.from(key, "base64").toString("utf8");
      if (decoded.includes("-----BEGIN")) {
        return decoded;
      }
    } catch {
      // Not base64, continue
    }
  }

  // Replace escaped newlines with actual newlines
  return key.replace(/\\n/g, "\n");
}
